
#change the image tag before you deploy, if using minikube, please use any tag other than "latest"
apiVersion: apps/v1
kind: Deployment
metadata:
  name: offers-deployment
  labels:
    app: offers
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offers
  template:
    metadata:
      labels:
        app: offers
    spec:
      containers:
        - name: offers
          image: networknt/com.networknt.ob.offers-3.1.2:3.1.2
          ports:
            - containerPort: 8443
          resources:
            requests:
              memory: "64Mi"
              #0.25 cpu
              cpu: "250m"
            limits:
              #0.5 cpu
              memory: "128Mi"
              cpu: "500m"
          #cannot use httpcheck due to the server can be https
          readinessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: offers-service
  labels:
    app: offers
spec:
  selector:
    app: offers
  type: NodePort
  ports:
    - protocol: TCP
      port: 8443